#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#
# send commands to jupyter kernel
#

# USAGE:
#   echo 'a=1' | ./jpsnd      # send to most recent kernel
#   echo 'a=1' | ./jpsnd 2289 # send to specific kernel
# Find kernels:
#   ls /run/user/$(id -u)/jupyter
#   %connect_info


import jupyter_client
import sys

if len(sys.argv) < 2:
    cf = jupyter_client.find_connection_file()
else:
    cf = jupyter_client.find_connection_file(sys.argv[1])
km = jupyter_client.BlockingKernelClient(connection_file=cf)
km.load_connection_file()

send = sys.stdin.read()
if len(send) > 0:
    km.execute(send)
else:
    # TODO: paste from clipboard if nothing in pipe
    pass
