#!/usr/bin/env bash
#
# deal with i3 workspaces:
#
# $0                            # prompt for command:
# $0 "rename workspace to"      # rename current
# $0 "workspace"                # move to or create a new empty workspace (and go there)
# $0 "move container workspace" # move current window to named space

# get or set i3 command
cmd="$@"
[ -z $cmd ] && read junk cmd <<< $(echo -e "jp\nworkspace|mv\nmove container workspace|rename\nrename workspace to" | rofi -sep '|' -eh 2 -dmenu -p "action:")
[ -z "$cmd" ] && exit 

echo $cmd
i3-msg $cmd $(i3-msg -t get_workspaces|jq  '.[].name'|rofi -dmenu -i -p "workspace:" )
